name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/redvers/pony-dependency-builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: build-binary
        run: make static
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            jndi-file-scanner
            Release.txt
