name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  superlinter:
    name: Lint bash, docker, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MD: true
          VALIDATE_YAML: true

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Verify CHANGELOG
        uses: docker://ghcr.io/ponylang/changelog-tool:release
        with:
          args: changelog-tool verify

  test-static:
    name: Test Alpine Static Generation
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/redvers/pony-dependency-builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: alpine specific
        run: echo 'use "lib:lzma"' > alpine.pony
      - name: build-binary
        run: make static
