name: Release Notes

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - .release-notes/next-release.md
      - .release-notes/\d+.\d+.\d+.md

permissions:
  packages: read
  pull-requests: read
  contents: write

jobs:
  release-notes:
    runs-on: ubuntu-latest
    name: Update release notes
    steps:
      - name: Update
        uses: docker://ghcr.io/ponylang/release-notes-bot-action:0.3.10
        with:
          GIT_USER_NAME: "redvers"
          GIT_USER_EMAIL: "red@contact.red"
        env:
          API_CREDENTIALS: ${{ secrets.GITHUB_TOKEN }}

